### ISSUE TITLE
Failed to load glyph, with error: invalid composite glyph

### ISSUE THREAD

**Issue by Anonrate** [kovidgoyal/kitty#133]
I was looking through the source code of FontForge with Vim, and all of a sudden it just closed.  I was using Kitty.  I wasn't running it through another terminal sadly so I didn't see any output.

I then was compiling FontForge and I have compiled FontForge plenty of times with Kitty without it crashing, and I noticed it crashed again.  So I decided to run kitty through Konsole so I could see some output.

I go to compile FontForge again, and I see this.

Traceback (most recent call last):
  File "./kitty/fonts/render.py", line 84, in render_cell_wrapper
    first, second = render_cell(text, bold, italic, underline, strikethrough)
  File "./kitty/fonts/render.py", line 55, in render_cell
    first, second = rc(text, bold, italic)
  File "./kitty/fonts/freetype.py", line 257, in render_cell
    bitmap_char = render_char(text, bold, italic, width)
  File "./kitty/fonts/freetype.py", line 180, in render_char
    return render_using_face(font, face, text, width, italic, bold)
  File "./kitty/fonts/freetype.py", line 129, in render_using_face
    bitmap = render_to_bitmap(font, face, text)
  File "./kitty/fonts/freetype.py", line 118, in render_to_bitmap
    load_char(font, face, text)
  File "./kitty/fonts/freetype.py", line 30, in load_char
    face.load_char(text, font.hinting, font.hintstyle)
ValueError: Failed to load glyph, with error: invalid composite glyph
Rendering of a cell failed, aborting

The font is a TrueType font.  Not bitmap.  Actually it's the font that I had opened an issue on before becuase it wasn't working as it was a bitmap.  Except I decided to port it over to be TrueType with outlines.  Took more than 3 months, but I finally got it to look how I wanted it.

To use the font that I'm using, I have it and the source in my repo called TerminusHybrid.

**Comment by kovidgoyal** [comment]
I just committed code to not crash when failing to render a glyph. It should also print out what text it was trying to render. THat should tell you what the problem glyph in your font is.

**Comment by Anonrate** [comment]
Look like I'm going to have to take a look my font, but the issue is still happening and it is crashing.  Output is as follows:

Failed to render text: 'ë' with error: Failed to load glyph, with error: invalid composite glyph
Segmentation fault

**Comment by kovidgoyal** [comment]
I'd need a stacktrace to se where the crash is happening. Compile kitty with

./setup.py --debug

and use

echo bt | coredumpctl gdb

**Comment by kovidgoyal** [comment]
Incidentally, on my system with freetype 2.8.1 and the ttf font file from your repository rendering of ë works fine,
![screenshot_20170930_074742](https://user-images.githubusercontent.com/1308621/31041484-ac2744e6-a5b3-11e7-9022-a3855d4ed03f.png)

**Comment by Anonrate** [comment]
I should probably use the updated version of my font.   Lol.  I work on it so much I don't bother to reinstall it.  Thanks for the response though.  If it does somehow happen again, I will be sure to provide you with that info.
