### ISSUE TITLE
Incomplete rendering of graphical symbols

### ISSUE THREAD

**Issue by FvD** [kovidgoyal/kitty#165]
I'm not sure if these are also called emojis, but some of the graphical symbols used by zsh and neovim do not render properly. A part of them is cut off.

These are examples in kitty

![screen shot 2017-11-07 at 10 44 04](https://user-images.githubusercontent.com/2441145/32507393-e3679228-c3ac-11e7-96a5-07b0bdfe6741.png)

And these examples in neovim running on kitty

![screen shot 2017-11-07 at 10 43 46](https://user-images.githubusercontent.com/2441145/32507411-f47aa00a-c3ac-11e7-8fda-a5fbb27b2254.png)

All this on OSX using kitty version 0.4.2. I read through #73 but don't know enough about kitty or opengl to assess whether they are related.

**Comment by kovidgoyal** [comment]
OS X has an ancient wcwidth(). You can either tell kitty to use its internal wcwidth() via the config or beg Apple to update its software. Or picka  font that renders whatever those characters actually are in a nrrow form. Or use linux :) 

Note that using internal wcwidth means that what kitty thinks is a character cell and what the program running in kitty thinks is a character cell may differ, leading to other problems.

**Comment by kovidgoyal** [comment]
Oh and I shoudl add, you can probably achieve a similar result to what you get on linux (the wide characters being scaled down to fit in a single cell) by implementing a scaling transform on the core graphics surface, see line 255 in core_text.m. However, this looks pretty bad, so I am not particularly motivated to implement it. The proper fix is for APple to update its wcwidth() implementation so that it returns 2 instead of 1 or -1 for emojis.

**Comment by FvD** [comment]
This has been solved in version 0.5.0!

**Comment by kovidgoyal** [comment]
Yeah that's because OSX now uses the linux rendering path, so glyphs that dont fit are auto-scaled.

**Comment by CaptnBlubber** [comment]
I still have this issue with 0.6.1.
I tried both `use_system_wcwidth no` and `use_system_wcwidth yes`.

Font is patched [SourceCodePro](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro)

Here are the screenshots:
<img width="277" alt="screenshot1" src="https://user-images.githubusercontent.com/878307/34729183-49efef32-f55c-11e7-90b3-7514daa0b0e7.png">
<img width="939" alt="screenshot2" src="https://user-images.githubusercontent.com/878307/34729184-4a090f8a-f55c-11e7-9277-8b1847140abc.png">

**Comment by kovidgoyal** [comment]
Read the FAQ entry on it. https://github.com/kovidgoyal/kitty#some-special-symbols-are-rendered-small-truncated-in-kitty in particular the part about private use unicode symbols.
