### ISSUE TITLE
Opening and closing kitty windows in stacking mode in sway causes terminal windows to freeze for a few seconds

### ISSUE THREAD

**Issue by vishnumad** [kovidgoyal/kitty#1767]
Opening and closing multiple kitty windows in stacking mode in sway causes terminal windows to freeze for a few seconds. This only occurs in the stacking layout and when kitty windows are launched in single instance mode. 

Kitty version: 0.14.2
OS version: Arch linux
Window Manager: Sway

**Comment by kovidgoyal** [comment]
This should alreadybe fixed by https://github.com/kovidgoyal/kitty/commit/3fb00f6c70e2f575357c5812222442c79dead755

let me know if not.

**Comment by vishnumad** [comment]
The problem still occurs for me with the latest version built from source. Here's a [demo of the problem](https://streamable.com/ye8qd) if that helps. Left is kitty in single instance mode, middle is kitty in normal mode, and right is gnome-terminal.

**Comment by kovidgoyal** [comment]
OK I will take a look, but i am not a sway user, so can you post a minimal sway config and set of steps to reproduce.

**Comment by vishnumad** [comment]
[Here](https://gist.github.com/vishnumad/30bde654566a7f9d610e5c58a9ee68da) is the default sway config modified to open `kitty --single-instance` when pressing Mod(Win key)+Enter. The config file goes in ~/.config/sway/ and should be named config.

**Steps to reproduce**

1. Enter "Stacking mode" by pressing Mod+s
2. Press Mod+enter repeatedly to open kitty windows. You should be able to see the delay.

**Comment by kovidgoyal** [comment]
Thanks, will look at it when I have a moment.

**Comment by kovidgoyal** [comment]
Hmm am not able to reproduce with that config file and those steps. But
on the other hand there have been lots of changes/fixes to the event
loop in master, so maybe the issue is gone. Retry with HEAD and let me
know.
