### ISSUE TITLE
Mac osx app does not seem to start 

### ISSUE THREAD

**Issue by giulioungaretti** [kovidgoyal/kitty#349]
If I move the .app to anywhere and run it, the icon appears for a second then disappears.

But if I actually do  in another terminal app 
```sh
 /Applications/kitty.app/Contents/MacOS/kitty
```
Then it runs. I get the following output 
```
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation.
```

is it me / my system weird ?

**Comment by kovidgoyal** [comment]
Look in console.app to see why it isn't starting. And it would help if you told us what version of macOS you are running.

**Comment by giulioungaretti** [comment]
@kovidgoyal will do in a sec! Thanks for developing this, it's pretty amazing !

**Comment by giulioungaretti** [comment]
This is what I can find in console.app for kitty.

<img width="1318" alt="screen shot 2018-02-27 at 09 14 16" src="https://user-images.githubusercontent.com/2694199/36717538-bf5def40-1b9e-11e8-81af-9165e9f1dc6a.png">


Osx version: 10.13.3 (17D102).

**Comment by kovidgoyal** [comment]
You sure that is all there is? That's just the exit notification. You can also try running it as

open -a /Applications/kitty.app

**Comment by giulioungaretti** [comment]
@kovidgoyal to be honest I am not entirely sure, but if I search for kitty that's the only thing that shows up.

If if run kitty like this: `open -a /Applications/kitty.app`, then app starts up just fine without any error.

**Comment by kovidgoyal** [comment]
Open console.app before runnign kitty, click clear, then run kitty, see what messages/errors/warnings are logged.

**Comment by giulioungaretti** [comment]
sweet: that's what I see now (the error posted before does not show up now).
<img width="817" alt="screen shot 2018-02-27 at 15 34 31" src="https://user-images.githubusercontent.com/2694199/36734439-cc2d9dd0-1bd3-11e8-80a6-4d2202cc6322.png">

**Comment by kovidgoyal** [comment]
Nothing useful there. Look at the errors and faults section.

**Comment by Rockster1501** [comment]
Hi bud. If you run Kitty 0.8.0 in Mac OS you have to change command lines 11-30 for powersymbols where "-" is present replace with "_". After changing all run ktty test before apllying to Mac. Hope all works . Please keep me informed.
Tx

**Comment by kutsan** [comment]
I was having the same error and changing `┇` in your config to something different solves the problem magically.

```
tab_separator " ┇"
```

**Comment by kovidgoyal** [comment]
That would imply that for some reason launch services is operating in a non-UTF-8 environment on your machine. In any case, https://github.com/kovidgoyal/kitty/commit/721595ef04183f613fa00ba5b8d227a7fa2862fc should take care of it.

**Comment by kutsan** [comment]
But did this solve @giulioungaretti's problem?

**Comment by giulioungaretti** [comment]
@koekeishiya @kutsan  changing the tab separator makes the app start but can break other stuff. 
I will check again and debug more once a new release is out with 721595e  included!

**Comment by kutsan** [comment]
@giulioungaretti Breaks which stuff? Also, you can compile yourself, which isn't that hard.

**Comment by giulioungaretti** [comment]
@kutsan funny enough if I use your fix, then the shell it not run in login mode see #247 by default.

Anyway @kovidgoyal  thanks for the fix and @kutsan thanks for the tips.

Last commit from master works beautifully!

**Comment by kutsan** [comment]
@giulioungaretti In any case, you are welcome and I'm glad it's solved now.

**Comment by liuchengxu** [comment]
Hello, I'm still seeing these messages. How can I get rid of them?

I build kitty from the source and run `python3 .`. [Here](https://github.com/liuchengxu/dotfiles/blob/2d3aace556577d1ae2acdc542eff1f8187d741e9/kitty.conf) is my kitty.conf, if that helps, nothing special, just the color changes.

```bash
~/.../kovidgoyal/kitty ❯❯❯ python3 .
[146 20:24:44.435602] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation
[146 20:24:49.821698] [PARSE ERROR] Unknown OSC code: 50
[146 20:25:39.245018] [PARSE ERROR] Unknown OSC code: 50
```

**Comment by liuchengxu** [comment]
Thanks for your quick response! @kovidgoyal make sense now. Great work btw!

**Comment by mrillusi0n** [comment]
I was facing the same issue on macOS Catalina. I observed that it occurs when installed via `brew`. Installing the app via DMG solved it for me.

**Comment by Sayan-Manna** [comment]
Same issue on m1 macs as well, will it affect hardware acceleration?

**Comment by rish501** [comment]
How do we know if hardware acceleration is enabled and functioning?

**Comment by 7flash** [comment]
I can see this warning on macbook m2 should i be worried? anything i can do to improve performance?

WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation

**Comment by kovidgoyal** [comment]
On Thu, Jul 04, 2024 at 11:53:52PM -0700, Igor Berlenko wrote:
> I can see this warning on macbook m2 should i be worried? anything i can do to improve performance?
>
> WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation

No, its a limitation of apple's opengl drivers, it wont make any
practical difference to your usage of kitty, as this particular code
path is not hot (basically its updating of font glyph on the GPU that
needs to only happen once per new glyph seen in a kitty window).
