### ISSUE TITLE
cursor_shape is being ignored in 0.24.0

### ISSUE THREAD

**Issue by mil-ad** [kovidgoyal/kitty#4438]
I _think_ there's been a regression in 0.24.0 and `cursor_shape` is now being ignored. I only see the beam no matter what I set it to.

**Environment details**
```
kitty 0.24.0 created by Kovid Goyal
Linux milad-ryzen 5.10.89-1-lts #1 SMP Sun, 02 Jan 2022 19:43:44 +0000 x86_64
Arch Linux 5.10.89-1-lts (/dev/tty1)

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/milad/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.97
cursor_beam_thickness 2.0
disable_ligatures     2
font_family           IBM Plex Mono Medium
font_size             12.0
symbol_map:
	U+0621 - U+06cc → Vazir-Code-WOL
window_padding_width  FloatEdges(left=5.0, top=2.5, right=5.0, bottom=2.5)
Added mouse actions:
	 ctrl+b1 repeat ungrabbed mouse_click_url
	 ctrl+b1 repeat grabbed mouse_click_url
Added shortcuts:
	shift+up scroll_line_up
	shift+down scroll_line_down
	shift+page_up scroll_page_up
	shift+page_down scroll_page_down
	shift+home scroll_home
	shift+end scroll_end
	alt+c copy_to_clipboard
	alt+v paste_from_clipboard
	ctrl+- change_font_size all -1.0
	ctrl+0 change_font_size all 0
	ctrl+= change_font_size all +1.0
Colors:
	background            #21222d   
	color0                #1d2021   
	color1                #cc241d   
	color10               #b8bb26   
	color11               #fabd2f   
	color12               #99c6ca   
	color13               #d3869b   
	color14               #7ec16e   
	color15               #ebdbb2   
	color2                #98971a   
	color3                #d79921   
	color4                #458588   
	color5                #b16286   
	color6                #689d6a   
	color7                #a89984   
	color8                #928374   
	color9                #f42c3e   
	cursor                #d79921   
	foreground            #f2e5bc   
	selection_background  #d79921   
	selection_foreground  #1d2021   

```

**Comment by wrynegade** [comment]
I seem to be having the same issue, but a downgrade does not seem to fix this. I did notice if I use a multiplexer like `tmux`, the settings take hold... so maybe the desktop environment is now taking priority over the `kitty.conf`?

I was hoping to make a PR, but I'm new to the code-base and don't know whether this tracks.

**Comment by Luflosi** [comment]
Add `shell_integration no-cursor` to your config file. See https://sw.kovidgoyal.net/kitty/shell-integration.

**Comment by wrynegade** [comment]
> Add `shell_integration no-cursor` to your config file. See https://sw.kovidgoyal.net/kitty/shell-integration.

Interesting! Do you have any idea why zsh respects the cursor options in tmux even without this setting?

**Comment by Luflosi** [comment]
Because the shell integration is not active by default in tmux, you would need to do that manually.

**Comment by Luflosi** [comment]
@kovidgoyal can you pin this issue so it's easier to find for people who didn't read the FAQ, which will hopefully result in less of these bug reports?

**Comment by kovidgoyal** [comment]
sure.

**Comment by jannewulf** [comment]
I think there's still a bug. However, I am not sure if I understand the intended behavior here correctly, correct me if I'm wrong. The documentation of the [`no-cursor`](https://sw.kovidgoyal.net/kitty/shell-integration/#configuration) setting says that the intended behavior of the cursor replacement is that it is only replaced when the user is editing a command. Not sure what 'editing a command' means here, but I see the beam cursor at all times with `shell-integration enabled` (regardless of my settings of [`cursor-shape`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape)). As I understand it, the cursor replacement is buggy as it sets the `cursor-shape` to beam and then doesn't set it back to the users config when the 'command editing' is done.

This results in a situation where the default setting for [`shell-integration`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell_integration) overrides the `cursor-shape` setting. So simply setting the `cursor-shape` on a fresh kitty installation/configuration does not have any effect. Even if this is intended, I find it really confusing.

**Comment by kovidgoyal** [comment]
I cannot reproduce in 0.24.2. the cursor is restored to the value in cursor_shape when the shell command is executed.

**Comment by page-down** [comment]
> ... Not sure what 'editing a command' means here ...

For example, when you enter the shell's vi mode's normal mode, you will not see beam.

> ... and then doesn't set it back to the users config ...

Before executing the command, it will be set to the default value configured by `cursor-shape`. (Technically, set to `zero` unset.)

- In the terminal, any program, at any time, can set the cursor shape by escape sequences.
- `cursor-shape` is used to configure the shape of the final fallback if no cursor shape escape sequence is used in the current terminal session.
- Shell integration, which brings a beam-shaped cursor when entering shell commands.

`cursor-shape` is never used to set the shape that the cursor holds at any time. Once again, this is a final fallback value.
The reason it seemed to work before is that the shells or programs you use never configure the cursor shape.

> Even if this is intended, I find it really confusing.

I can understand your confusion. However there isn't an option to completely disable cursor changes and keeping one shape.
But there is still an option to disable the cursor shape changes in shell integration.

**Comment by jannewulf** [comment]
I've recorded what happens, so you can see what I was talking about. Maybe it is indeed expected behavior.

I understand that another program can change the cursor. But what I described happens right after I open kitty.
With the following settings, it shows the block cursor. Just like I expected it.
```
cursor_shape block
shell_integration enabled no-cursor
```
![term-2022-02-06_15-37_54](https://user-images.githubusercontent.com/7462597/152686043-f6b26a88-697b-4cdd-95f1-5b262f026fab.gif)

With the following settings, it shows the beam cursor. This is where I expected the block cursor, too.
```
cursor_shape block
shell_integration enabled
```
There did not run any program except for the ones that set my prompt and started this recording. But these did run before both recordings. So the only thing that changed is the `shell_integration` setting.
![term-2022-02-06_15-35_45](https://user-images.githubusercontent.com/7462597/152686083-509bba9c-f9a5-49d9-bdc9-af80dbaacfc8.gif)
If I am in the command editing mode here, it indeed does what the documentation says. But I don't think I am.

**Comment by page-down** [comment]
> If I am in the command editing mode here ...

Take bash as an example.

https://www.gnu.org/software/bash/manual/html_node/Command-Line-Editing.html

> Command line editing is enabled by default when using an interactive shell, ...

**Comment by kovidgoyal** [comment]
On Sun, Feb 06, 2022 at 06:59:10AM -0800, Janne Wulf wrote:
> If I am in the command editing mode here, it indeed does what the documentation says. But I don't think I am.

Yes, you are. If you can type ls and press enter to run ls, you are in
command editing mode.

**Comment by jannewulf** [comment]
Okay, sorry. It does what the documentation says. However, I still think that the solution is not optimal because the default settings for `shell_integration` overrides the `cursor_shape` setting. So, when a user wants to change the cursor, he/she has to change two settings. 

I have two suggestions that would make the situation less confusing IMHO:
- As I understand the documentation, the motivation for setting the cursor to beam in shell integration is that the user could position the cursor with the mouse. Maybe it would be better to only change the cursor to beam when it is positioned by mouse. When it is at the end of the user input it could be changed back to the `cursor_shape`.
- Or do not set the cursor shape in shell integration but set the default `cursor_shape` to beam. And let the cursor shape be only controlled by `cursor_shape`.

**Comment by ahmedelgabri** [comment]
I have the same issue only on one machine out of two machines sharing the same exact config. I'm configuring shell integration manually. So `kitty.conf` has `shell_integration disabled` & the manual config is 

```zsh
if test -n "$KITTY_INSTALLATION_DIR"; then
  export KITTY_SHELL_INTEGRATION="no-cursor"
  autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
  kitty-integration
  unfunction kitty-integration
fi
```

Both of these are 100% identical on both machines, yet one is showing a beam, and the other is showing a block.

**Comment by kovidgoyal** [comment]
If the two machines are showing different things then something about
them must be different. Most likely KITTY_INSTALLATION_DIR

**Comment by randomgeek78** [comment]
I am having an issue where the `shell_integration no-cursor` option is being ignored in 0.25.0. If I revert back to 0.24.4, it works fine.

**Comment by kovidgoyal** [comment]
With what shell? What OS?

**Comment by randomgeek78** [comment]
This is my info for debugging purposes-

```
kitty 0.25.0 created by Kovid Goyal
Linux mega 5.16.11-76051611-generic #202202230823~1646248261~20.04~2b22243-Ubuntu SMP PREEMPT Thu Ma x86_64
Pop!_OS 20.04 LTS mega /dev/tty

DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/popos/.local/kitty.app/bin/kitty
  base dir: /home/popos/.local/kitty.app/lib/kitty
  extensions dir: /home/popos/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/popos/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control y
bold_font            MonoLisa Bold
bold_italic_font     MonoLisa Bold Italic
enable_audio_bell    False
enabled_layouts      ['splits', 'stack']
font_family          MonoLisa Regular
font_size            11.2
italic_font          MonoLisa Regular Italic
listen_on            unix:/tmp/kty
shell_integration    frozenset({'no-cursor'})
symbol_map:
	U+e0a0 - U+e0a3 → Fira Code Regular Nerd Font Complete
	U+e0c0 - U+e0c7 → Fira Code Regular Nerd Font Complete
	U+e725 - U+e725 → Fira Code Regular Nerd Font Complete
Changed mouse actions:
	right press ungrabbed → mouse_select_command_output
	shift+right press ungrabbed → paste_from_selection
Added shortcuts:
	ctrl+h → kitten pass_keys.py neighboring_window left   ctrl+h
	ctrl+j → kitten pass_keys.py neighboring_window bottom ctrl+j
	ctrl+k → kitten pass_keys.py neighboring_window top    ctrl+k
	ctrl+l → kitten pass_keys.py neighboring_window right  ctrl+l
	ctrl+shift+' → launch --location=hsplit --copy-env --cwd=current
Changed shortcuts:
	ctrl+shift+5 → launch --location=vsplit --copy-env --cwd=current
	ctrl+shift+enter → new_window_with_cwd
Colors:
	background           #282c34   
	color0               #282c34   
	color1               #e06c75   
	color10              #56b6c2   
	color11              #e5c07b   
	color12              #61afef   
	color13              #be5046   
	color14              #56b6c2   
	color15              #abb2bf   
	color2               #98c379   
	color3               #e5c07b   
	color4               #61afef   
	color5               #be5046   
	color6               #56b6c2   
	color7               #979eab   
	color8               #393e48   
	color9               #d19a66   
	foreground           #979eab   
	selection_background #979eab   
	selection_foreground #282c34   

Important environment variables seen by the kitty process:
	PATH                                /home/popos/.pyenv/bin:/home/popos/.local/bin:/home/popos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :1
	USER                                popos
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_MENU_PREFIX                     gnome-
	XDG_CURRENT_DESKTOP                 pop:GNOME
	XDG_SESSION_DESKTOP                 pop
	XDG_DATA_DIRS                       /usr/share/pop:/home/popos/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-pop:/etc/xdg
```

**Comment by kovidgoyal** [comment]
I cannot reproduce with bash on my linux system. This is caused by something in your ~/.bashrc or ~/.bash_profile or similar, bisect it to find the culprit.

**Comment by bootc** [comment]
> I am having an issue where the `shell_integration no-cursor` option is being ignored in 0.25.0. If I revert back to 0.24.4, it works fine.

I'm seeing the same thing on macOS with 0.25.0. My cursor is a pipe/bar rather than a block as I'd like it to be. I have `shell_integration no-cursor` and `cursor_shape block` configured. My shell is bash. I get exactly the same effect using `kitty --config=NONE -o 'shell_integration no-cursor' -o shell=bash`. This used to work in 0.24.4, but changed with 0.25.0.

**Comment by kovidgoyal** [comment]
The only way I can think of that happening is if your bashrc is changing IFS to something weird like - or a letter. Like I said above, bisect it. Or try https://github.com/kovidgoyal/kitty/commit/7788f48dd5f09506953c73f77cb71ce7f1b2f897

**Comment by saligrama** [comment]
Having the same issue on Arch Linux on version 0.25.0 running zsh. Here's the debug info:

```
kitty 0.25.0 created by Kovid Goyal
Linux ampere 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64
Arch Linux 5.17.1-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/asaligrama/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control  y
cursor_blink_interval 0.0
enable_audio_bell     False
font_family           Fira Code Retina
initial_window_height (30, 'cells')
initial_window_width  (80, 'cells')
kitty_mod             6
linux_display_server  x11
remember_window_size  False
shell_integration     frozenset({'invalid'})
window_padding_width  FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	ctrl+alt++ → change_font_size all +2.0
	ctrl+alt+, → move_tab_backward
	ctrl+alt+- → change_font_size all -2.0
	ctrl+alt+. → move_tab_forward
	ctrl+alt+0 → tenth_window
	ctrl+alt+1 → first_window
	ctrl+alt+2 → second_window
	ctrl+alt+3 → third_window
	ctrl+alt+4 → fourth_window
	ctrl+alt+5 → fifth_window
	ctrl+alt+6 → sixth_window
	ctrl+alt+7 → seventh_window
	ctrl+alt+8 → eighth_window
	ctrl+alt+9 → ninth_window
	ctrl+alt+= → change_font_size all +2.0
	ctrl+alt+[ → previous_window
	ctrl+alt+] → next_window
	ctrl+alt+` → move_window_to_top
	ctrl+alt+a > 1 → set_background_opacity 1
	ctrl+alt+a > d → set_background_opacity default
	ctrl+alt+a > l → set_background_opacity -0.1
	ctrl+alt+a > m → set_background_opacity +0.1
	ctrl+alt+b → move_window_backward
	ctrl+alt+c → copy_to_clipboard
	ctrl+alt+e → open_url_with_hints
	ctrl+alt+f → move_window_forward
	ctrl+alt+g → show_last_command_output
	ctrl+alt+h → show_scrollback
	ctrl+alt+j → scroll_line_down
	ctrl+alt+k → scroll_line_up
	ctrl+alt+l → next_layout
	ctrl+alt+n → new_os_window
	ctrl+alt+o → pass_selection_to_program
	ctrl+alt+p > f → kitten hints --type path --program -
	ctrl+alt+p > h → kitten hints --type hash --program -
	ctrl+alt+p > l → kitten hints --type line --program -
	ctrl+alt+p > n → kitten hints --type linenum
	ctrl+alt+p > w → kitten hints --type word --program -
	ctrl+alt+p > y → kitten hints --type hyperlink
	ctrl+alt+p > shift+f → kitten hints --type path
	ctrl+alt+q → close_tab
	ctrl+alt+r → start_resizing_window
	ctrl+alt+s → paste_from_selection
	ctrl+alt+t → set_tab_title
	ctrl+alt+u → kitten unicode_input
	ctrl+alt+v → paste_from_clipboard
	ctrl+alt+w → close_window
	ctrl+alt+x → scroll_to_prompt 1
	ctrl+alt+z → scroll_to_prompt -1
	ctrl+alt+escape → kitty_shell window
	ctrl+alt+enter → new_window
	ctrl+alt+backspace → change_font_size all 0
	ctrl+alt+delete → clear_terminal reset active
	ctrl+alt+left → previous_tab
	ctrl+alt+right → next_tab
	ctrl+alt+up → scroll_line_up
	ctrl+alt+down → scroll_line_down
	ctrl+alt+page_up → scroll_page_up
	ctrl+alt+page_down → scroll_page_down
	ctrl+alt+home → scroll_home
	ctrl+alt+end → scroll_end
	ctrl+alt+f2 → edit_config_file
	ctrl+alt+f5 → load_config_file
	ctrl+alt+f6 → debug_config
	ctrl+alt+f7 → focus_visible_window
	ctrl+alt+f8 → swap_with_window
	ctrl+alt+f10 → toggle_maximized
	ctrl+alt+f11 → toggle_fullscreen
	ctrl+alt+kp_subtract → change_font_size all -2.0
	ctrl+alt+kp_add → change_font_size all +2.0
Removed shortcuts:
	ctrl+shift++ → change_font_size all +2.0
	ctrl+shift+, → move_tab_backward
	ctrl+shift+- → change_font_size all -2.0
	ctrl+shift+. → move_tab_forward
	ctrl+shift+0 → tenth_window
	ctrl+shift+1 → first_window
	ctrl+shift+2 → second_window
	ctrl+shift+3 → third_window
	ctrl+shift+4 → fourth_window
	ctrl+shift+5 → fifth_window
	ctrl+shift+6 → sixth_window
	ctrl+shift+7 → seventh_window
	ctrl+shift+8 → eighth_window
	ctrl+shift+9 → ninth_window
	ctrl+shift+= → change_font_size all +2.0
	ctrl+shift+[ → previous_window
	ctrl+shift+] → next_window
	ctrl+shift+` → move_window_to_top
	ctrl+shift+a > 1 → set_background_opacity 1
	ctrl+shift+a > d → set_background_opacity default
	ctrl+shift+a > l → set_background_opacity -0.1
	ctrl+shift+a > m → set_background_opacity +0.1
	ctrl+shift+b → move_window_backward
	ctrl+shift+c → copy_to_clipboard
	ctrl+shift+e → open_url_with_hints
	ctrl+shift+f → move_window_forward
	ctrl+shift+g → show_last_command_output
	ctrl+shift+h → show_scrollback
	ctrl+shift+j → scroll_line_down
	ctrl+shift+k → scroll_line_up
	ctrl+shift+l → next_layout
	ctrl+shift+n → new_os_window
	ctrl+shift+o → pass_selection_to_program
	ctrl+shift+p > f → kitten hints --type path --program -
	ctrl+shift+p > h → kitten hints --type hash --program -
	ctrl+shift+p > l → kitten hints --type line --program -
	ctrl+shift+p > n → kitten hints --type linenum
	ctrl+shift+p > w → kitten hints --type word --program -
	ctrl+shift+p > y → kitten hints --type hyperlink
	ctrl+shift+p > shift+f → kitten hints --type path
	ctrl+shift+q → close_tab
	ctrl+shift+r → start_resizing_window
	ctrl+shift+s → paste_from_selection
	ctrl+shift+t → new_tab
	ctrl+shift+u → kitten unicode_input
	ctrl+shift+v → paste_from_clipboard
	ctrl+shift+w → close_window
	ctrl+shift+x → scroll_to_prompt 1
	ctrl+shift+z → scroll_to_prompt -1
	ctrl+shift+escape → kitty_shell window
	ctrl+shift+enter → new_window
	ctrl+shift+backspace → change_font_size all 0
	ctrl+shift+delete → clear_terminal reset active
	ctrl+shift+left → previous_tab
	ctrl+shift+right → next_tab
	ctrl+shift+up → scroll_line_up
	ctrl+shift+down → scroll_line_down
	ctrl+shift+page_up → scroll_page_up
	ctrl+shift+page_down → scroll_page_down
	ctrl+shift+home → scroll_home
	ctrl+shift+end → scroll_end
	ctrl+shift+f2 → edit_config_file
	ctrl+shift+f5 → load_config_file
	ctrl+shift+f7 → focus_visible_window
	ctrl+shift+f8 → swap_with_window
	ctrl+shift+f10 → toggle_maximized
	ctrl+shift+f11 → toggle_fullscreen
	ctrl+shift+kp_subtract → change_font_size all -2.0
	ctrl+shift+kp_add → change_font_size all +2.0
	ctrl+shift+alt+t → set_tab_title
Colors:
	background            #32302f   
	color0                #32302f   
	color1                #fb4934   
	color10               #b8bb26   
	color11               #fabd2f   
	color12               #83a598   
	color13               #d3869b   
	color14               #8ec07c   
	color15               #fbf1c7   
	color2                #b8bb26   
	color3                #fabd2f   
	color4                #83a598   
	color5                #d3869b   
	color6                #8ec07c   
	color7                #d5c4a1   
	color8                #665c54   
	color9                #fb4934   
	cursor                #d5c4a1   
	foreground            #d5c4a1   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/home/asaligrama/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                asaligrama
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 i3-gnome
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Comment by bootc** [comment]
OK it wasn't because of IFS being wrong (it wasn't). It was because my .bashrc had the old shell integration code still in it, so kitty.bash was sourced twice. The first time it did the right thing, but the second time around KITTY_SHELL_INTEGRATION wasn't set so the cursor was the default pipe.

**Comment by kovidgoyal** [comment]
@saligrama search for shell_integration in your own debug output

**Comment by saligrama** [comment]
Turns out it needed to be `no-cursor` rather than `no_cursor`, not sure why this only ended up being an issue with 0.25.0 vs previous versions.

**Comment by page-down** [comment]
> Turns out it needed to be `no-cursor` rather than `no_cursor` ... not sure why this only ended up being an issue ...

`no_cursor` is never a valid option value.
In older versions, when `whatever_invalid` is configured, it is equivalent to clearing `KITTY_SHELL_INTEGRATION`, so shell integration is never enabled.
This is fixed in the new version.

**Comment by ahmedelgabri** [comment]
I updated to `0.25.0` same issue, still exists, one machine is working fine with a block cursor & the other is not…

**Comment by kovidgoyal** [comment]
Since you have disabled shell integration in both machines, your cursor change is not coming from kitty.

**Comment by page-down** [comment]
> I updated to 0.25.0 same issue, still exists ...

https://github.com/ahmedelgabri/dotfiles/blob/40d2941e36f680dde1a7f736f00cf9636dfbc003/config/zsh.d/.zshrc#L97-L102

I see that your dotfiles are manually configured with shell integration with zsh.

Is there anything else that affects this? For example, clear the zsh configuration to include only the kitty shell integration and see if the problem still exists.

**Comment by ahmedelgabri** [comment]
> Since you have disabled shell integration in both machines, your cursor change is not coming from kitty.

If that's the case shouldn't all other apps be affected too? But they all work fine, Alacrrity, Terminal.app

**Comment by kovidgoyal** [comment]
> > Since you have disabled shell integration in both machines, your cursor change is not coming from kitty.
> 
> If that's the case shouldn't all other apps be affected too? But they all work fine, Alacrrity, Terminal.app

As @page-down pointed out you have enabled it manually in zshrc, it's not coming from kitty.

**Comment by charbelnicolas** [comment]
I also have the same problem, I haven't changed a thing in my configuration from latest version and I can't get kitty to show the block shape for the cursor.

**Comment by randomgeek78** [comment]
> 

This worked for me. I had this in my `.bashrc` and after removing it, things worked with 0.25.0. These lines did not cause issues with 0.24. What would be the recommendation regarding these lines to be in `.bashrc`?

**Comment by kovidgoyal** [comment]
From the changelog:

Bash integration: No longer modify .bashrc to load shell integration.
  It is recommended to remove the lines used to load the shell integration from :file:`~/.bashrc`
