### ISSUE TITLE
Tmux in kitty behave weird

### ISSUE THREAD

**Issue by nippyin** [kovidgoyal/kitty#5174]
**Describe the bug**
After running brew update noticed kitty terminal with tmux does not work as expected.

**To Reproduce**
1. Open kitty.
2. run tmux new -s new-session

Following message appears and if press any key for example press d it will print ➜  ~ dsddsd

Cannot read termcap database;
using dumb terminal settings.
 

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
kitty 0.25.1 created by Kovid Goyal
Darwin mac-muser 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/muser/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style     (True, False)
adjust_line_height        3
background_opacity        0.9
click_interval            0.3
copy_on_select            clipboard
cursor_blink_interval     0.0
cursor_shape              3
disable_ligatures         2
editor                    nvim
enabled_layouts           ['tall:bias=65', 'fat:bias=65', 'stack', 'grid', 'horizontal', 'vertical']
font_family               Hack Nerd Font Mono
font_size                 17.0
hide_window_decorations   True
inactive_text_alpha       0.8
scrollback_lines          3000
select_by_word_characters :-./_~?&=%+#
strip_trailing_spaces     smart
tab_bar_margin_width      3.0
term                      xterm-256color
window_border_width       (0, 'pt')
window_margin_width       FloatEdges(left=4.0, top=4.0, right=4.0, bottom=4.0)
window_padding_width      FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)
Removed shortcuts:
	ctrl+shift+6 → sixth_window
Changed shortcuts:
	ctrl+shift+0 → goto_layout stack
	ctrl+shift+8 → goto_layout fat:bias=65
	ctrl+shift+9 → goto_layout tall:bias=65
	ctrl+shift+[ → previous_tab
	ctrl+shift+] → next_tab
	ctrl+shift+b → scroll_page_up
	ctrl+shift+f → scroll_page_down
	ctrl+shift+h → send_text all \x1b\x62
	ctrl+shift+j → previous_window
	ctrl+shift+k → next_window
	ctrl+shift+l → send_text all \x1b\x66
	ctrl+shift+t → new_tab_with_cwd
	ctrl+shift+enter → new_window_with_cwd
	ctrl+shift+left → send_text all \x01
	ctrl+shift+right → send_text all \x05
	ctrl+shift+up → move_window_forward
	ctrl+shift+down → move_window_backward
Colors:
	active_border_color       #666666   
	active_tab_background     #bbbbbb   
	active_tab_foreground     #282828   
	background                #011627   
	color0                    #282828   
	color1                    #f43753   
	color10                   #c9d05c   
	color11                   #ffc24b   
	color12                   #b3deef   
	color13                   #d3b987   
	color14                   #73cef4   
	color2                    #c9d05c   
	color3                    #ffc24b   
	color4                    #b3deef   
	color5                    #d3b987   
	color6                    #73cef4   
	color7                    #eeeeee   
	color8                    #484848   
	color9                    #f43753   
	cursor                    #ffffff   
	foreground                #acb4c2   
	inactive_border_color     #333333   
	inactive_tab_background   #282828   
	inactive_tab_foreground   #eeeeee   
	selection_background      #ebdbb2   
	selection_foreground      #655b53   
	url_color                 #d65c0d   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.FMf3sfv0lf/org.xquartz:0
	USER                                muser

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
This is addressed in the kitty FAQ. Reboot your computer.

**Comment by nippyin** [comment]
> s is addressed in the kitty FAQ. Reboot your compu

thanks for prompt reply, i already tried rebooting macOS however issue still persists. also referred https://sw.kovidgoyal.net/kitty/faq/#i-am-using-tmux-and-have-a-problem


Not quite following what exactly I need to do to make it work, Before brew update it used to work for years with same config. 

Thanks for helping.

**Comment by kovidgoyal** [comment]
No clue then. I dont use tmux.
