### ISSUE TITLE
sessions are buggy

### ISSUE THREAD

**Issue by Mister7F** [kovidgoyal/kitty#9328]
First, thanks for this amazing terminal, it's by far my favorite, I would like to play with session, but it's very buggy.
I'm on kitty 0.45.0

I have 2 sessions
```
new_tab
cd ~/Projects/config/
launch --title="1"

new_tab
launch --title="2"


new_tab
launch --title="3"
```

and 
```
new_tab
cd ~/Projects/CTF/
launch
```

I don't want the tab to be visible if I have only 1 in the current session, so I did
```
tab_bar_min_tabs 2
tab_bar_filter session:~ or session:^$
```

When jumping from one session to an other, the tab if the previous sessions are still visible (but we cannot click on them)
https://drive.google.com/file/d/1QoP-YqB5rFOjda2O8ZqcDjUG2f7fxaO-/view?usp=sharing

Also, if you first open a session with 2 tabs, then open a session with 2, go to the first session, close one tab
=> the tab bar is hidden, which is good

Jump to the second session, the tab bar glitch
https://drive.google.com/file/d/168Ewe2fAH9v3WznQf8FfnhxExIEOrXS9/view?usp=sharing

**Comment by kovidgoyal** [comment]
dup of #9278

**Comment by Mr7F** [comment]
@kovidgoyal I have the bug in 0.45.0, and the fix in https://github.com/kovidgoyal/kitty/issues/9278 has been merged in that version, so the issue still exists?

**Comment by kovidgoyal** [comment]
Then open a new issue and this time fill in the issue template so I know exactly what version and system etc you are running. And note that if you want the tab bar to be hidden when only one tab is visible, the correct value for tab_bar_min_tabs is 1 not 2.

**Comment by Mr7F** [comment]
> if you want the tab bar to be hidden when only one tab is visible, the correct value for tab_bar_min_tabs is 1 not 2

Why is the default 2?
https://github.com/kovidgoyal/kitty/blob/cc55c04034848de703ad5c4f094e66051094eb9d/kitty/options/types.py#L641

(and when I test, 2 work but not 1)

> so I know exactly what version

it was the second line of my message... :/ anyway I won't use session, it was just for playing and I found those bugs

**Comment by kovidgoyal** [comment]
Does not replicate for me with

```sh
kitty --config=None -o 'tab_bar_filter session:~ or session:^$' -o 'map f1 goto_session /t/s'
```
With two sessions in /t/s one with one tab one with three tabs.

Opening session with three tabs shows tab bar. Opening session with single tab hides tab bar. Going back to session with three tabs shows tab bar again, as expected. Again, follow the issue template. I really don't have the time to extract every detail from you one post at a time.

I did find an issue with closing a non session tab once opening the session with a single tab. But that's not relevant.

**Comment by kovidgoyal** [comment]
And the issue I noticed with closing non session tab is fixed by: https://github.com/kovidgoyal/kitty/commit/95c1f5aca52522cabdd001d9514681297742e4b6

**Comment by leandergangso** [comment]
Hey, as it seems that this is not fixed. I wanted to give some feedback and clear steps to reproduce the bug.

I made a simple script that will reproduce the tab rendering issue, in doing so i discovered another bug, where the tab is blinking.

### Tab render bug

https://github.com/user-attachments/assets/5661cd55-3ed1-4e4a-83ab-42a26f2738fe

<details open>
<summary>Script seen in the video</summary>

```bash
#!/usr/bin/env bash

# setup
mkdir /tmp/gitlab_issue_9555

cat <<EOF > /tmp/gitlab_issue_9555/one.session
new_tab one
launch bash
EOF

cat <<EOF > /tmp/gitlab_issue_9555/two.session
new_tab two
launch bash
EOF

# kitty config
kitty --config=None \
    -o 'tab_bar_filter session:~ or session:^$' \
    -o 'tab_bar_min_tabs 0' \
    -o 'tab_bar_edge top' \
    -o 'startup_session /tmp/gitlab_issue_9555/one.session' \
    -o 'map space goto_session /tmp/gitlab_issue_9555/two.session'

# teardown
rm -rf /tmp/gitlab_issue_9555
```

**run the script then press 'space' to open the new session, then write 'exit' to see the bug**

</details>

### Blinking bug

https://github.com/user-attachments/assets/65da2ff7-3e20-4553-af54-df13a2e94663

<details open>
<summary>Script seen in the video</summary>

```bash
#!/usr/bin/env bash

# setup
mkdir /tmp/gitlab_issue_9555

cat <<EOF > /tmp/gitlab_issue_9555/one.session
new_tab one
launch bash
EOF

cat <<EOF > /tmp/gitlab_issue_9555/two.session
new_tab two
launch bash
EOF

# kitty config
kitty --config=None \
    -o 'tab_bar_filter session:~ or session:^$' \
    -o 'tab_bar_edge top' \
    -o 'startup_session /tmp/gitlab_issue_9555/one.session' \
    -o 'map space goto_session /tmp/gitlab_issue_9555/two.session'

# teardown
rm -rf /tmp/gitlab_issue_9555
```

**run the script then press 'space' to open the new session, sees the bug immediately**

</details>

**Comment by kovidgoyal** [comment]
You need to be running nightly to get the fix, are you?

**Comment by leandergangso** [comment]
i have ran `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=nightly` but `path/to/kitty.app/bin/kitty -v` still says 0.45.0 so perhaps thats not right?

**Comment by kovidgoyal** [comment]
press ctrl+shift+f6 and you will see the commit hash that kitty is built against if you are running nightly. For the current nightly it should be dba73e82be

**Comment by kovidgoyal** [comment]
Your script doesnt repro for me running from master

**Comment by leandergangso** [comment]
yes the commit matches: `kitty 0.45.0 (dba73e82be) created by Kovid Goyal`

tested my scripts again, both seem to be fixed...  
i might have ran tests against the old version then.

sorry for the mishap and thanks.

ps: really like the new sessions that "recently" came out
